// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHotelWebAPI.BazaDanych;

#nullable disable

namespace MyHotelWebAPI.Migrations
{
    [DbContext(typeof(MyHotelWebDB))]
    [Migration("20250120020531_Init2")]
    partial class Init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Client", b =>
                {
                    b.Property<int>("Client_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_ID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<int>("Postal_Code")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Client_ID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Event", b =>
                {
                    b.Property<int>("Event_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Event_ID"), 1L, 1);

                    b.Property<int>("Date")
                        .HasColumnType("int");

                    b.Property<int>("Position_ID")
                        .HasColumnType("int");

                    b.Property<int>("Priotity")
                        .HasColumnType("int");

                    b.Property<int>("Room_ID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Event_ID");

                    b.HasIndex("Position_ID");

                    b.HasIndex("Room_ID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Hotel", b =>
                {
                    b.Property<int>("Hotel_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Hotel_ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Hotel_ID");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Payment", b =>
                {
                    b.Property<int>("Payment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_ID"), 1L, 1);

                    b.Property<int>("Date")
                        .HasColumnType("int");

                    b.Property<string>("Payment_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Payment_ID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Position", b =>
                {
                    b.Property<int>("Position_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Position_ID"), 1L, 1);

                    b.Property<bool>("On_Shift")
                        .HasColumnType("bit");

                    b.Property<string>("Position_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Position_ID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Reservation", b =>
                {
                    b.Property<int>("Reservation_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Reservation_ID"), 1L, 1);

                    b.Property<int>("Client_ID")
                        .HasColumnType("int");

                    b.Property<int>("MoveIn")
                        .HasColumnType("int");

                    b.Property<int>("MoveOut")
                        .HasColumnType("int");

                    b.Property<int>("Payment_ID")
                        .HasColumnType("int");

                    b.Property<int>("Room_ID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Reservation_ID");

                    b.HasIndex("Client_ID");

                    b.HasIndex("Payment_ID");

                    b.HasIndex("Room_ID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Room", b =>
                {
                    b.Property<int>("Room_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Room_ID"), 1L, 1);

                    b.Property<int>("Availaibility")
                        .HasColumnType("int");

                    b.Property<int>("Hotel_ID")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Room_ID");

                    b.HasIndex("Hotel_ID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Staff", b =>
                {
                    b.Property<int>("Staff_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Staff_ID"), 1L, 1);

                    b.Property<bool>("On_Shift")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position_ID")
                        .HasColumnType("int");

                    b.HasKey("Staff_ID");

                    b.HasIndex("Position_ID");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Event", b =>
                {
                    b.HasOne("MyHotelWebAPI.BazaDanych.Position", "Position")
                        .WithMany("Events")
                        .HasForeignKey("Position_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyHotelWebAPI.BazaDanych.Room", "Room")
                        .WithMany("Events")
                        .HasForeignKey("Room_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Reservation", b =>
                {
                    b.HasOne("MyHotelWebAPI.BazaDanych.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("Client_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyHotelWebAPI.BazaDanych.Payment", "Payment")
                        .WithMany("Reservations")
                        .HasForeignKey("Payment_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyHotelWebAPI.BazaDanych.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("Room_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Payment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Room", b =>
                {
                    b.HasOne("MyHotelWebAPI.BazaDanych.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("Hotel_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Staff", b =>
                {
                    b.HasOne("MyHotelWebAPI.BazaDanych.Position", "Position")
                        .WithMany("Staff")
                        .HasForeignKey("Position_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Payment", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Position", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Room", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
