// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHotelWebAPI.BazaDanych;

#nullable disable

namespace MyHotelWebAPI.Migrations
{
    [DbContext(typeof(MyHotelWebDB))]
    [Migration("20250123113716_Alfa1.2")]
    partial class Alfa12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Client", b =>
                {
                    b.Property<int>("Client_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_ID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Postal_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Client_ID");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Client_ID = 1,
                            Address = "Warsaw, ul.Podluzna 5",
                            Email = "JanKowalski@gmail.com",
                            Name = "Jan Kowalski",
                            Password = "clientpass1",
                            Phone = 123456789,
                            Postal_Code = "00-001",
                            Type = "Single"
                        },
                        new
                        {
                            Client_ID = 2,
                            Address = "Krakow, ul.Krakowska 10",
                            Email = "ANowak@gmail.com",
                            Name = "Anna Nowak",
                            Password = "clientpass2",
                            Phone = 987654321,
                            Postal_Code = "30-200",
                            Type = "Group"
                        });
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Event", b =>
                {
                    b.Property<int>("Event_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Event_ID"), 1L, 1);

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int>("Position_ID")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Room_ID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Event_ID");

                    b.HasIndex("Position_ID");

                    b.HasIndex("Room_ID");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Event_ID = 1,
                            Date = "2025/1/14",
                            IsDone = true,
                            Position_ID = 1,
                            Priority = 1,
                            Room_ID = 1,
                            Type = "Naprawa"
                        },
                        new
                        {
                            Event_ID = 2,
                            Date = "2025/1/18",
                            IsDone = false,
                            Position_ID = 2,
                            Priority = 3,
                            Room_ID = 2,
                            Type = "Sprzątanie"
                        },
                        new
                        {
                            Event_ID = 3,
                            Date = "2025/1/20",
                            IsDone = false,
                            Position_ID = 1,
                            Priority = 2,
                            Room_ID = 1,
                            Type = "Przegląd"
                        });
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Hotel", b =>
                {
                    b.Property<int>("Hotel_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Hotel_ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Hotel_ID");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Hotel_ID = 1,
                            Name = "Marriott"
                        },
                        new
                        {
                            Hotel_ID = 2,
                            Name = "DS1 Olimp"
                        });
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Payment", b =>
                {
                    b.Property<int>("Payment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_ID"), 1L, 1);

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Payment_ID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Payment_ID = 1,
                            Date = "2025/1/17",
                            Payment_type = "Card",
                            Price = 550,
                            Status = "Paid"
                        },
                        new
                        {
                            Payment_ID = 2,
                            Date = "2025/1/18",
                            Payment_type = "Cash",
                            Price = 100,
                            Status = "Waiting"
                        });
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Position", b =>
                {
                    b.Property<int>("Position_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Position_ID"), 1L, 1);

                    b.Property<string>("Position_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Position_ID");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Position_ID = 1,
                            Position_Type = "Receptionist"
                        },
                        new
                        {
                            Position_ID = 2,
                            Position_Type = "Developer"
                        },
                        new
                        {
                            Position_ID = 3,
                            Position_Type = "Maintance"
                        });
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Reservation", b =>
                {
                    b.Property<int>("Reservation_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Reservation_ID"), 1L, 1);

                    b.Property<int>("Client_ID")
                        .HasColumnType("int");

                    b.Property<string>("MoveIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Payment_ID")
                        .HasColumnType("int");

                    b.Property<int>("Room_ID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Reservation_ID");

                    b.HasIndex("Client_ID");

                    b.HasIndex("Payment_ID");

                    b.HasIndex("Room_ID");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Reservation_ID = 1,
                            Client_ID = 1,
                            MoveIn = "2025/1/10",
                            MoveOut = "2025/1/17",
                            Payment_ID = 1,
                            Room_ID = 2,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Reservation_ID = 2,
                            Client_ID = 2,
                            MoveIn = "2025/2/1",
                            MoveOut = "2025/2/9",
                            Payment_ID = 2,
                            Room_ID = 4,
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Room", b =>
                {
                    b.Property<int>("Room_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Room_ID"), 1L, 1);

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<int>("Hotel_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Room_ID");

                    b.HasIndex("Hotel_ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Room_ID = 1,
                            Availability = true,
                            Hotel_ID = 1,
                            Name = "Pokój 100",
                            Price = 350,
                            Type = "Single"
                        },
                        new
                        {
                            Room_ID = 2,
                            Availability = false,
                            Hotel_ID = 1,
                            Name = "Pokój 110",
                            Price = 550,
                            Type = "Double"
                        },
                        new
                        {
                            Room_ID = 3,
                            Availability = true,
                            Hotel_ID = 1,
                            Name = "Pokój 120",
                            Price = 800,
                            Type = "Apartment"
                        },
                        new
                        {
                            Room_ID = 4,
                            Availability = false,
                            Hotel_ID = 2,
                            Name = "Pokój 310",
                            Price = 100,
                            Type = "Single"
                        },
                        new
                        {
                            Room_ID = 5,
                            Availability = true,
                            Hotel_ID = 2,
                            Name = "Pokój 212",
                            Price = 150,
                            Type = "Double"
                        },
                        new
                        {
                            Room_ID = 6,
                            Availability = true,
                            Hotel_ID = 2,
                            Name = "Pokój 1008",
                            Price = 200,
                            Type = "Apartment"
                        },
                        new
                        {
                            Room_ID = 7,
                            Availability = true,
                            Hotel_ID = 1,
                            Name = "Pokój 200",
                            Price = 350,
                            Type = "Single"
                        },
                        new
                        {
                            Room_ID = 8,
                            Availability = true,
                            Hotel_ID = 1,
                            Name = "Pokój 210",
                            Price = 550,
                            Type = "Double"
                        },
                        new
                        {
                            Room_ID = 9,
                            Availability = true,
                            Hotel_ID = 1,
                            Name = "Pokój 220",
                            Price = 800,
                            Type = "Apartment"
                        },
                        new
                        {
                            Room_ID = 10,
                            Availability = true,
                            Hotel_ID = 2,
                            Name = "Pokój 350",
                            Price = 100,
                            Type = "Single"
                        },
                        new
                        {
                            Room_ID = 11,
                            Availability = true,
                            Hotel_ID = 2,
                            Name = "Pokój 212",
                            Price = 150,
                            Type = "Double"
                        },
                        new
                        {
                            Room_ID = 12,
                            Availability = true,
                            Hotel_ID = 2,
                            Name = "Pokój 1008",
                            Price = 200,
                            Type = "Apartment"
                        },
                        new
                        {
                            Room_ID = 13,
                            Availability = true,
                            Hotel_ID = 1,
                            Name = "Pokój 200",
                            Price = 350,
                            Type = "Single"
                        },
                        new
                        {
                            Room_ID = 14,
                            Availability = true,
                            Hotel_ID = 1,
                            Name = "Pokój 410",
                            Price = 550,
                            Type = "Double"
                        },
                        new
                        {
                            Room_ID = 15,
                            Availability = true,
                            Hotel_ID = 1,
                            Name = "Pokój 420",
                            Price = 800,
                            Type = "Apartment"
                        },
                        new
                        {
                            Room_ID = 16,
                            Availability = true,
                            Hotel_ID = 2,
                            Name = "Pokój 450",
                            Price = 100,
                            Type = "Single"
                        },
                        new
                        {
                            Room_ID = 17,
                            Availability = true,
                            Hotel_ID = 2,
                            Name = "Pokój 512",
                            Price = 150,
                            Type = "Double"
                        },
                        new
                        {
                            Room_ID = 18,
                            Availability = true,
                            Hotel_ID = 2,
                            Name = "Pokój 1008",
                            Price = 200,
                            Type = "Apartment"
                        },
                        new
                        {
                            Room_ID = 19,
                            Availability = true,
                            Hotel_ID = 1,
                            Name = "Pokój 090",
                            Price = 350,
                            Type = "Single"
                        },
                        new
                        {
                            Room_ID = 20,
                            Availability = true,
                            Hotel_ID = 1,
                            Name = "Pokój 0960",
                            Price = 550,
                            Type = "Double"
                        });
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Staff", b =>
                {
                    b.Property<int>("Staff_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Staff_ID"), 1L, 1);

                    b.Property<string>("On_Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position_ID")
                        .HasColumnType("int");

                    b.HasKey("Staff_ID");

                    b.HasIndex("Position_ID");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Staff_ID = 1,
                            On_Shift = "Day",
                            Password = "secret1",
                            Position_ID = 2
                        },
                        new
                        {
                            Staff_ID = 2,
                            On_Shift = "Night",
                            Password = "secret2",
                            Position_ID = 2
                        },
                        new
                        {
                            Staff_ID = 3,
                            On_Shift = "Day",
                            Password = "secret3",
                            Position_ID = 1
                        });
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Event", b =>
                {
                    b.HasOne("MyHotelWebAPI.BazaDanych.Position", "Position")
                        .WithMany("Events")
                        .HasForeignKey("Position_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyHotelWebAPI.BazaDanych.Room", "Room")
                        .WithMany("Events")
                        .HasForeignKey("Room_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Reservation", b =>
                {
                    b.HasOne("MyHotelWebAPI.BazaDanych.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("Client_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyHotelWebAPI.BazaDanych.Payment", "Payment")
                        .WithMany("Reservations")
                        .HasForeignKey("Payment_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyHotelWebAPI.BazaDanych.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("Room_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Payment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Room", b =>
                {
                    b.HasOne("MyHotelWebAPI.BazaDanych.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("Hotel_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Staff", b =>
                {
                    b.HasOne("MyHotelWebAPI.BazaDanych.Position", "Position")
                        .WithMany("Staff")
                        .HasForeignKey("Position_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Payment", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Position", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("MyHotelWebAPI.BazaDanych.Room", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
